import requests
import urllib.parse

def generate_explanation(drug_name: str, disease_name: str, shared_genes: list[str]) -> str:
    genes_str = ", ".join(shared_genes)
    prompt = f"Explain the biological mechanism of why the drug {drug_name} could potentially treat {disease_name}. Assume it acts on the following shared targets/genes involved in the disease: {genes_str}. Be scientific, professional, and concise (under 4 sentences). Do not mention that this is a hypothetical prompt or generated by AI."
    
    encoded_prompt = urllib.parse.quote(prompt)
    url = f"https://text.pollinations.ai/{encoded_prompt}?seed=42"
    
    try:
        response = requests.get(url, timeout=15)
        if response.status_code == 200:
            return response.text.strip()
        else:
            return f"Mechanistic explanation is currently unavailable (Status: {response.status_code})."
    except Exception as e:
        return "Explanation could not be generated due to a network error."
